### ISSUE TITLE
Sonar plugin issue

### ISSUE THREAD

**Issue by quichef** [RoadieHQ/marketing-site#1213]
Hey there, 

Got.a question. Sonarqube plugin doc is not super consistent between backstage repo and here. 
Details about configuring the proxy is not displayed in here https://github.com/backstage/backstage/blob/master/plugins/sonarqube-backend/README.md 

and the conf between app-config.yaml are not consitent :
in https://roadie.io/backstage/plugins/sonarqube/
```yaml
proxy:
'/sonarqube':
  target: https://your.sonarqube.instance.com/api
  allowedMethods: ['GET']
  auth: "${SONARQUBE_TOKEN}:"

**sonarQube**:  <----- with capital Q
  baseUrl: https://your.sonarqube.instance.com
```

on backstage repo :

```yaml
sonarqube:
  baseUrl: https://sonarqube.example.com
  apiKey: 123456789abcdef0123456789abcedf012
````

Is doc on Roadie's website the one to follow to make the plugin work? (currently failing tremendously on my local, issue probably located between my chair and my laptop, but anyway 😄 )
Cheers,
